free_pages/urls.py
from django.urls import path
from . import views
from .views import (
    SubCategoryListView,
    PostListView,
    PostDetailView,
    ContactFormView,
    FeedbackFormView,
    FormSuccessView,
    AboutView,
    MemberResourcesView,
    OfferingsView,
    ContactInfoView,
)

urlpatterns = [
    path("", views.home, name="home"),
    path("member-resources/", MemberResourcesView.as_view(), name="member_resources"),
    path(
        "member-resources/<slug:category_slug>/",
        SubCategoryListView.as_view(),
        name="subcategories",
    ),
    path(
        "member-resources/<slug:category_slug>/<slug:subcategory_slug>/",
        PostListView.as_view(),
        name="posts",
    ),
    path(
        "member-resources/<slug:category_slug>/<slug:subcategory_slug>/<slug:post_slug>/",
        PostDetailView.as_view(),
        name="post_detail",
    ),
    path("cleaning-services", OfferingsView.as_view(), name="cleaning_services"),
    path("feedback", FeedbackFormView.as_view(), name="feedback"),
    path("success", FormSuccessView.as_view(), name="form_success"),
    path("about", AboutView.as_view(), name="about"),
    path("contact-info/", ContactInfoView.as_view(), name="contact_info"),
    path("contact/", ContactFormView.as_view(), name="contact"),


]

holistic_hincher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

from free_pages import views
from free_pages.views import (
    ChangePasswordView,
    PasswordChangeSuccessView,
    PaymentCancelled,
    PaymentSuccess,
    SignUpView,
)

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", include("free_pages.urls")),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("payment-success/", PaymentSuccess.as_view(), name="payment_sucess"),
    path("payment-cancelled/", PaymentCancelled.as_view(), name="payment_cancelled"),
    path("create-customer-portal/", views.customer_portal, name="customer_portal"),
    path("webhook/", views.webhook_received, name="webhook"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path(
        "change-password/success/",
        PasswordChangeSuccessView.as_view(),
        name="change_password_success",
    ),
    path(
        "password-reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("payment/<price>", views.create_checkout_session, name="payment"),
    path("memberships/", views.list_memberships, name="memberships"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

free_pages/models.py
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class MembershipBenefits(models.Model):
    benefits = RichTextField()


class CustomUser(AbstractUser):
    stripe_customer_id = models.CharField(max_length=255, null=True, blank=True)
    is_member = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class MainCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    slug = AutoSlugField(unique=True, populate_from="name")

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(
        MainCategory, on_delete=models.CASCADE, related_name="subcategories"
    )
    name = models.CharField(max_length=50)
    description = models.TextField()
    slug = AutoSlugField(unique=True, populate_from="name")

    def __str__(self):
        return self.name


class Post(models.Model):
    main_category = models.ForeignKey(
        MainCategory, on_delete=models.CASCADE, related_name="posts"
    )
    subcategory = models.ForeignKey(
        SubCategory, on_delete=models.CASCADE, related_name="posts"
    )
    title = models.CharField(max_length=50)
    description = models.TextField()
    content = RichTextField()
    slug = AutoSlugField(unique=True, populate_from="title")
    file = models.FileField(
        upload_to="files", null=True, blank=True, help_text="Optional"
    )
    image = models.ImageField(
        upload_to="images", null=True, blank=True, help_text="Optional"
    )
    image_description = models.CharField(
        max_length=50,
        help_text="Describe the image for search engines and screen readers",
        blank=True,
        null=True,
    )
    video = models.FileField(
        upload_to="files", null=True, blank=True, help_text="Optional"
    )

    def __str__(self):
        return self.title

free_pages/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["placeholder"] = "Username"
        self.fields["username"].widget.attrs["style"] = "text-align:center;"

        self.fields["email"].widget.attrs["placeholder"] = "Email"
        self.fields["email"].widget.attrs["style"] = "text-align:center;"

        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].widget.attrs["style"] = "text-align:center;"

        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].widget.attrs["style"] = "text-align:center;"


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


CLEANING_FREQUENCIES = [
    ("one-off", "One-off"),
    ("weekly", "Weekly"),
    ("fortnightly", "Fortnightly"),
    ("monthly", "Monthly"),
]
CLEANING_TYPE = [
    ("house", "House"),
    ("office", "Office"),
    ("presale", "Pre-sale clean"),
    ("spring", "Spring Clean"),
    ("bond/exit", "Bond or Exit Clean"),
    ("mum", "Cleaning for First-time Mums"),
    ("oven", "Oven Clean"),
    ("declutter", "Declutter and Organise"),
    ("airbnb", "Air BnB Clean"),
    ("outside", "Outdoor Patio Clean"),
    ("other", "Other (specify below)"),
]
HOME_SIZE = [
    ("n/a", "N/A"),
    ("1-2 bed", "1-2 bedrooms"),
    ("3-5 bed", "3-5 bedrooms"),
    (">5 bed", "More than 5 bedrooms"),
]
OFFICE_SIZE = [
    ("n/a", "N/A"),
    ("5-10 people", "5-10 people"),
    ("11-15 people", "11-15 people"),
    (">15 people", "More than 15 people"),
]
OTHER_SERVICES = [
    ("yoga", "Private Yoga"),
    ("pet sit", "Pet Sitting"),
    ("meal prep", "Meal Preparation"),
    ("other", "Other (specify below)"),
]


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    mobile = forms.CharField(max_length=100)
    street_address = forms.CharField(
        label="Street Address of the property",
        max_length=250,
    )
    post_code = forms.CharField(max_length=10)
    clean_type = forms.ChoiceField(
        label="What type of clean are you after?",
        choices=CLEANING_TYPE,
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
    )
    clean_type = forms.MultipleChoiceField(
        choices=CLEANING_TYPE,
        label="What type of clean are you after?",
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    clean_frequency = forms.MultipleChoiceField(
        label="How often should we come?",
        choices=CLEANING_FREQUENCIES,
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    home_size = forms.ChoiceField(
        required=False,
        label="How many bedrooms in the home?",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=HOME_SIZE,
    )
    office_size = forms.ChoiceField(
        required=False,
        label="How many people use the office?",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=OFFICE_SIZE,
    )
    other_services = forms.MultipleChoiceField(
        label="Are you interested in any of our other services?",
        choices=OTHER_SERVICES,
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    additonal_information = forms.CharField(widget=forms.Textarea, required=False)


FEEDBACK_CATEGORIES = [
    ("cleaning", "Cleaning"),
    ("business_coaching", "Business Coaching"),
    ("website", "Website"),
    ("other", "Other"),
]
SATISFACTION_RATINGS = [
    ("", ""),
    ("very satisfied", "Very satisfied"),
    ("satisfied", "Satisfied"),
    ("neutral", "Neutral"),
    ("dissatisfied", "Dissatisfied"),
    ("very dissatisfied", "Very dissatisfied"),
]
CLEANLINESS_RATINGS = [
    ("", ""),
    ("excellent", "Excellent"),
    ("good", "Good"),
    ("average", "Average"),
    ("poor", "Poor"),
    ("very poor", "Very poor"),
]
INSTRUCTIONS_FOLLOWED = [
    ("", ""),
    ("yes", "Yes, completely"),
    ("partially", "Yes, but partially"),
    ("no", "No, not at all"),
]
AREAS = [
    ("", ""),
    ("dusting/vaccumming", "Dusting and vacuuming"),
    ("kitchen/bedroom", "Kitchen & Bathrooms"),
    ("extra/rotational", "Extras & rotational items"),
    ("helpful/friendly", "Helpful & friendly manner"),
]
RECCOMMENDATION_CHOICES = [
    ("", ""),
    ("yes", "Yes, definitley"),
    ("maybe", "Yes, maybe"),
    ("probably not", "No, probably not"),
    ("no", "No, defnitley not"),
]


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, help_text="(Optional)")
    feedback_category = forms.ChoiceField(
        label="What is your feedback about?",
        choices=FEEDBACK_CATEGORIES,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    feedback = forms.CharField(widget=forms.Textarea, required=False)
    satisfaction_rating = forms.ChoiceField(
        label="How satisfied were you with the overall cleaning service provided?",
        choices=SATISFACTION_RATINGS,
        required=False,
    )
    cleanliness_rating = forms.ChoiceField(
        label="How would you rate the cleanliness of your space after the cleaning?",
        choices=CLEANLINESS_RATINGS,
        required=False,
    )
    instructions_followed = forms.ChoiceField(
        label="Did the cleaner follow any specific instructions or requests you had given?",
        choices=INSTRUCTIONS_FOLLOWED,
        required=False,
    )
    areas_for_improvement = forms.ChoiceField(
        label="Areas for improvement",
        choices=AREAS,
        required=False,
    )
    areas_of_satisfaction = forms.ChoiceField(
        label="Areas of satisfaction",
        choices=AREAS,
        required=False,
    )
    would_reccommend = forms.ChoiceField(
        label="Would you recommend our cleaning services to others?",
        choices=RECCOMMENDATION_CHOICES,
        required=False,
    )
    additional_information = forms.CharField(
        label="Is there anything else you would like to share about your experience with our cleaning service?",
        widget=forms.Textarea,
        required=False,
    )
    contact_information = forms.CharField(
        label="Please provide your contact information if you would like us to follow up with you regarding your feedback",
        widget=forms.Textarea,
        required=False,
        help_text="Thank you for taking the time to complete this feedback form. We appreciate your input and look forward to serving you again in the future.",
    )

free_pages/templates/free_pages/about.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<meta
  name="description"
  content="Learn more about Holistic Hincher and their commitment to unpolluted, purifying, and wholesome home cleaning services. Discover the passion for green cleaning, top-quality cleaners, and eco-friendly products."
/>
{% endblock meta %} {% block title %} About Holistic Hincher 
{% endblock title %}
 {% block css_files %}
<link rel="stylesheet" href="{% static 'home.css' %}" />
<!-- You may need to include additional CSS files for styling specific to the "about" page. -->
{% endblock css_files %} {% block content %} 

{% include 'free_pages/includes/header.html' with page_title="About Holistic Hincher" %}
<div class="container-fluid bg-green">
  <div class="row justify-content-center mb-5">
    <div class="col-md-6 mb-3 rounded-3 bg-light p-4">
      <p>
        Jules's holistic approach is shaped by diverse experience and a profound
        understanding that where focus goes, energy flows.. With a journey that
        spans from New Zealand to South Africa and the UK, now settling in sunny
        Australia, Jules took the reins over from a long-standing cleaning
        business from E. Gibbs Manage my Place.
      </p>
      <p>
        Our mission is to bring the art of holistic solutions to your home and
        commercial, small business environments, or simply put “where passion
        and high vibing frequency converge to create transformative spaces”
      </p>

      <p>
        Our mission now is to bring the art of holistic solutions to your home
        and commercial environments.
      </p>
      <p>
        Inspired by the famous Mrs. Hinch, the Instagram sensation and British
        “cleanfluencer”, Holistic Hincher’s passion is in keeping things in
        tip-top condition, transforming all spaces which makes life easier.
      </p>

      <p>
        At Holistic Hincher, we go beyond surface-level aesthetics. We
        understand that a space has the power to nurture, inspire, and leave a
        lasting impression. Whether it's managing your home with care and
        attention to detail or transforming your small business and commercial
        space into welcoming havens, our focus is on crafting environments that
        radiate positive energy and promote well-being.
      </p>

      <p>
        Experience the transformative effects of our holistic approach as we
        merge the art of creating harmonious spaces with our unwavering support
        for small businesses. Let us help you elevate your space to new heights,
        where warmth, comfort, and success intertwine in perfect harmony.
      </p>
      <p>Discover the magic of Holistic Hincher today.</p>
    </div>
  </div>
</div>
{% endblock %}

free_pages/templates/free_pages/contact_form.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <meta name="description"
          content="Experience top-notch cleaning services for your home or office. Fill out our easy-to-use form to request professional house or office cleaning today. We make your space spotless and hassle-free.">
{% endblock meta %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock css_files %}
{% block title %}
    Contact
{% endblock title %}
{% block content %}
    {% include "free_pages/includes/header.html" with page_title='Contact Us' page_description='We take pride in our cleaning. Get in touch for a quote!' %}
    <div class="container-fluid bg-green">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 col-lg-3 d-flex bg-dark text-light my-4 mx-4 text-center justify-content-center">
                <div class="align-self-stretch box p-4 ">
                    <i class="bi bi-telephone fs-1"></i>
                    <h3 class="mb-4">Phone Number</h3>
                    <p>
                        <a href="tel://1234567920">+ 61 451 055 683</a>
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 d-flex bg-dark text-light my-4 text-center justify-content-center">
                <div class="align-self-stretch box p-4 text-center">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <span class="icon-paper-plane"></span>
                    </div>
                    <i class="bi bi-envelope fs-1"></i>
                    <h3 class="mb-4">Email Address</h3>
                    <p>
                        <a href="mailto:info@yoursite.com">hello@holistichincher.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
<div class="container-fluid bg-green">
    <div class="row p-3 justify-content-cetner">
        <div class="col-md-6 p-2 mx-auto">
            <div class="card bg-darkgreen text-light rounded-5">
                <div class="card-body mx-auto">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong> There were some problems with your submission.
                            {% for error in form.errors %}
                                <ul class="center-bullets">
                                    <li>{{ error }}</li>
                                </ul>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for pair in index_pairs %}
                            <div class="row">
                                {% for field in pair %}
                                    <div class="col">
                                        <p>{{ field.label_tag }}</p>
                                        <p>{{ field }}</p>
                                    </div>
                                    {% if field.errors %}
                                        <div class="text-warning">
                                            {% for error in field.errors %}{{ error }}{% endfor %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <div class="row justify-content-center align-items-center">
                            <div class="col-md-6 text-center d-flex justify-content-center mt-4">
                                <div class="g-recaptcha" data-sitekey="{{ site_key }}"></div>
                            </div>
                        </div>
                        <div class="row justify-content-center align-items-center my-4">
                            <div class="col-md-6 text-center">
                                <button id="submit-button"
                                        class="btn text-light btn-lg bg-green"
                                        type="submit">Send Enquiry</button>
                                <div class="spinner-border p-2" role="status" id="loadingSpinner">
                                    <span class="visually-hidden">Sending...</span>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script>
        $('#loadingSpinner').hide();

        $('form').submit(function(event) {
            $('#loadingSpinner').show();
        });            



</script>
{% endblock content %}

free_pages/templates/free_pages/contact_info.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<meta name="description" content="Contact information for Holistic Hincher." />
{% endblock meta %} {% block title %} Contact Holistic Hincher {% endblock title %}
{% block css_files %}
<link rel="stylesheet" href="{% static 'home.css' %}" />
{% endblock css_files %} 
{% block content %} 
{% include 'free_pages/includes/header.html' with page_title="Contact Holistic Hincher" %}

  <div class="container-fluid bg-green">
    <div class="row d-flex justify-content-center">
      <div class="col-md-6 col-lg-3 d-flex bg-dark text-light my-4 mx-4 text-center justify-content-center">
        <div class="align-self-stretch box p-4 ">
          <i class="bi bi-telephone fs-1"></i>

          <h3 class="mb-4">Phone Number</h3>
          <p><a href="tel://1234567920">+ 61 451 055 683</a></p>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 d-flex bg-dark text-light my-4 text-center justify-content-center">
        <div class="align-self-stretch box p-4 text-center">
          <div class="icon d-flex align-items-center justify-content-center">
            <span class="icon-paper-plane"></span>
          </div>
          <i class="bi bi-envelope fs-1"></i>

          <h3 class="mb-4">Email Address</h3>
          <p><a href="mailto:info@yoursite.com">hello@holistichincher.com</a></p>
        </div>
      </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

free_pages/templates/free_pages/feedback_form.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <meta name="description"
          content="Provide your valuable feedback to help us improve our services. Use our feedback form to share your thoughts and suggestions with us today." />
{% endblock meta %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock css_files %}
{% block title %}
    Feedback
{% endblock title %}
{% block content %}
    {% include "free_pages/includes/header.html" with page_title="Feedback" page_description="Got feedback? We'd love to hear it!" %}
    <div class="container-fluid align-items-center bg-green">
        <div class="row  p-3 justify-items-center">
            <div class="col-md-6 mx-auto ">
                <div class="card p-5 text-light bg-darkgreen rounded-5">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong> There were some problems with your submission.
                            {% for error in form.errors %}
                                <ul class="center-bullets">
                                    <li>{{ error }}</li>
                                </ul>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <p>{{ field.label_tag }}    {{ field }}</p>
                            <p>{{ field.help_text }}</p>
                            {% if field.errors %}
                                <div class="text-warning">
                                    {% for error in field.errors %}{{ error }}{% endfor %}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="row">
                            <div class="col-md-6 text-center d-flex my-4">
                                <div class="g-recaptcha" data-sitekey="{{ site_key }}"></div>
                            </div>
                        </div>
                        <button class="btn bg-green text-light btn-lg" type="submit">Send Feedback</button>
                        <div class="spinner-border p-2" role="status" id="loadingSpinner">
                            <span class="visually-hidden">Sending...</span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script>
            $(document).ready(function() {
                // Function to update the visibility of 'feedback' field and other fields
                function updateFeedbackVisibility() {
                    var selectedOption = $('#id_feedback_category').val();
                    var showFeedback = ['other', 'business_coaching', 'website'].includes(selectedOption);
                    var cleaningFeedback = [
                        'satisfaction_rating',
                        'cleanliness_rating',
                        'instructions_followed',
                        'areas_for_improvement',
                        'areas_of_satisfaction',
                        'would_reccommend',
                        'additional_information',
                        'contact_information'
                    ];
            
                    // Hide or show the 'feedback' field and its label
                    if (showFeedback) {
                        $('#id_feedback').show();
                        $('label[for="id_feedback"]').show();
                    } else {
                        $('#id_feedback').hide();
                        $('label[for="id_feedback"]').hide();
                    }
            
                    // Hide or show the fields in 'cleaningFeedback' based on 'showFeedback' value
                    for (var i = 0; i < cleaningFeedback.length; i++) {
                        var fieldName = cleaningFeedback[i];
                        if (showFeedback) {
                            $('#id_' + fieldName).hide();
                            $('label[for="id_' + fieldName + '"]').hide();
                        } else {
                            $('#id_' + fieldName).show();
                            $('label[for="id_' + fieldName + '"]').show();
                        }
                    }
                }
            
                // Initially hide the 'feedback' field and its label
                $('#id_feedback').hide();
                $('label[for="id_feedback"]').hide();
                $('#loadingSpinner').hide();



            
                // Attach a change event handler to the 'feedback_category' field
                $('#id_feedback_category').change(function() {
                    updateFeedbackVisibility();
                });

                $('form').submit(function(event) {
                    $('#loadingSpinner').show();
                });            
                
                updateFeedbackVisibility();
            });
    </script>
{% endblock content %}

free_pages/templates/free_pages/form_success.html
{% extends "base.html" %}
{% block title %}
    Thank You
{% endblock title %}
{% block meta %}
    <meta name="description"
          content="Your request has been successfully submitted! Thank you for choosing our cleaning services. We'll get to work making your space shine. Contact us for any further inquiries or assistance.">
{% endblock meta %}
{% block content %}
    {% include "free_pages/includes/header.html" with page_title="Success" page_description="Your message has been sent." %}
{% endblock content %}

free_pages/templates/free_pages/member_resources.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
  <meta name="description"
        content="Unlock a wealth of knowledge with Holistic Hincher's exclusive member resources. Explore main content categories designed to elevate your business, including strategy insights, industry trends, leadership development, and more. Empower your journey to business success today.">
{% endblock meta %}
{% block title %}
  Member Resources
{% endblock title %}
{% block css_files %}
  <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock css_files %}
{% block content %}
  {% include 'free_pages/includes/header.html' with page_title='Member Resources' page_description='Exclusive content for your business' %}
  <div class="container-fluid bg-green">
    <div class="row align-items-center justify-content-center">
      {% for category in main_categories %}
        <div class="col-md-6 p-5 text-center">
          <div class="card bg-darkgreen text-light mx-auto" style="width: 18rem">
            {% if category.posts.all.0.image %}
              <img src="{{ category.posts.all.0.image.url }}"
                   class="card-img-top p-2 rounded-4"
                   height="200px"
                   width="250px"
                   alt="{{ category.posts.all.0.image_description }}">
            {% endif %}
            <div class="card-body">
              <h1 class="card-title">{{ category.name }}</h1>
              <p class="card-text lead">{{ category.description }}</p>
            </div>
            <div class="btn-group p-4">
              <a href="{% url "subcategories" category.slug %}">
                <button type="button" class="btn bg-green text-light">Explore Categories</button>
              </a>
              <button type="button"
                      class="btn bg-green text-light dropdown-toggle dropdown-toggle-split"
                      data-bs-toggle="dropdown"
                      aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                {% for subcategory in category.subcategories.all %}
                  <li>
                    <a class="dropdown-item"
                       href="{% url 'posts' category_slug=category.slug subcategory_slug=subcategory.slug %}">{{ subcategory.name }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}